import { trpc } from "@/lib/trpc";
import { BarChart3, CalendarDays, LineChart as LineChartIcon, UsersRound } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

function dateLabel(value: string | null | undefined) { return value ? new Intl.DateTimeFormat("ko-KR", { month: "long", day: "numeric", weekday: "short" }).format(new Date(`${value}T12:00:00`)) : "아직 출석 기록 없음"; }

export default function Analytics() {
  const { data, isLoading } = trpc.analytics.overview.useQuery(undefined, { retry: false });
  const hasData = Boolean(data?.trend.length);
  return <div className="space-y-6">
    <header><p className="text-xs font-bold tracking-[0.14em] text-[#b66b3d]">ATTENDANCE INSIGHTS</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight text-stone-800 sm:text-3xl">출석 통계</h1><p className="mt-2 text-sm text-stone-500">주별 전체 흐름과 최근 주차의 기수별 출석률을 비교합니다.</p></header>
    <section className="grid gap-3 sm:grid-cols-3"><Summary label="출석 대상" value={isLoading ? "—" : `${data?.totalMembers ?? 0}명`} icon={<UsersRound className="h-5 w-5" />} /><Summary label="분석 기준" value={isLoading ? "—" : dateLabel(data?.latestDate)} icon={<CalendarDays className="h-5 w-5" />} compact /><Summary label="최근 기록" value={isLoading ? "—" : `${data?.trend.length ?? 0}주`} icon={<BarChart3 className="h-5 w-5" />} /></section>
    {!hasData && !isLoading ? <EmptyAnalytics /> : <section className="grid gap-5 xl:grid-cols-2"><ChartCard title="주별 전체 출석 추이" subtitle="최근 8주 · 출석 인원 기준" icon={<LineChartIcon className="h-5 w-5" />}><ResponsiveContainer width="100%" height={300}><LineChart data={data?.trend ?? []} margin={{ top: 12, left: -18, right: 12, bottom: 0 }}><CartesianGrid stroke="#eeeae1" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fill: "#8c877d", fontSize: 12 }} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fill: "#8c877d", fontSize: 12 }} /><Tooltip contentStyle={{ borderRadius: 14, border: "1px solid #e7e4dc", boxShadow: "0 10px 24px rgba(50,50,40,.1)" }} labelFormatter={(_, items) => items?.[0]?.payload?.fullDate ?? ""} formatter={(value: number) => [`${value}명`, "출석"]} /><Line type="monotone" dataKey="present" stroke="#2d6a4f" strokeWidth={3} dot={{ r: 4, fill: "#2d6a4f", strokeWidth: 2, stroke: "#fff" }} activeDot={{ r: 6 }} /></LineChart></ResponsiveContainer></ChartCard><ChartCard title="기수/부서별 출석률" subtitle={`기준: ${dateLabel(data?.latestDate)}`} icon={<BarChart3 className="h-5 w-5" />}><ResponsiveContainer width="100%" height={300}><BarChart data={data?.groupRates ?? []} margin={{ top: 12, left: -18, right: 12, bottom: 0 }}><CartesianGrid stroke="#eeeae1" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="group" axisLine={false} tickLine={false} tick={{ fill: "#8c877d", fontSize: 12 }} /><YAxis domain={[0, 100]} tickFormatter={value => `${value}%`} axisLine={false} tickLine={false} tick={{ fill: "#8c877d", fontSize: 12 }} /><Tooltip contentStyle={{ borderRadius: 14, border: "1px solid #e7e4dc", boxShadow: "0 10px 24px rgba(50,50,40,.1)" }} formatter={(value: number, _name, props) => [`${value}% (${props.payload.present}/${props.payload.total}명)`, "출석률"]} /><Bar dataKey="rate" fill="#d68750" radius={[7, 7, 0, 0]} maxBarSize={46} /></BarChart></ResponsiveContainer></ChartCard></section>}
    {hasData && <section className="rounded-[1.6rem] border border-[#e7e4dc] bg-white p-5 shadow-[0_8px_25px_rgba(68,62,48,0.04)]"><div className="flex items-center justify-between"><div><p className="font-bold text-stone-800">기수별 상세 현황</p><p className="mt-1 text-xs text-stone-500">최근 출석 주차 기준</p></div><span className="rounded-xl bg-[#e8f0e8] px-3 py-1.5 text-xs font-bold text-[#214e3b]">{dateLabel(data?.latestDate)}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data?.groupRates.map(group => <div key={group.group} className="rounded-2xl bg-[#f8f7f3] p-4"><div className="flex items-center justify-between"><p className="font-bold text-stone-700">{group.group}</p><p className="text-lg font-extrabold text-[#214e3b]">{group.rate}%</p></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#e5e3dc]"><div className="h-full rounded-full bg-[#2d6a4f]" style={{ width: `${group.rate}%` }} /></div><p className="mt-2 text-xs text-stone-500">{group.present}명 출석 / {group.total}명 대상</p></div>)}</div></section>}
  </div>;
}
function Summary({ label, value, icon, compact }: { label: string; value: string; icon: React.ReactNode; compact?: boolean }) { return <div className="rounded-[1.5rem] border border-[#e7e4dc] bg-white p-5 shadow-[0_6px_20px_rgba(68,62,48,0.04)]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e8f0e8] text-[#214e3b]">{icon}</span><p className={`mt-4 font-extrabold tracking-tight text-stone-800 ${compact ? "text-lg" : "text-3xl"}`}>{value}</p><p className="mt-1 text-xs font-semibold text-stone-500">{label}</p></div>; }
function ChartCard({ title, subtitle, icon, children }: { title: string; subtitle: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-[1.6rem] border border-[#e7e4dc] bg-white p-5 shadow-[0_8px_25px_rgba(68,62,48,0.04)] sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-bold text-stone-800">{title}</h2><p className="mt-1 text-xs text-stone-500">{subtitle}</p></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#fff0df] text-[#b66b3d]">{icon}</span></div><div className="mt-5">{children}</div></section>; }
function EmptyAnalytics() { return <section className="rounded-[1.6rem] border border-dashed border-[#cfcbbf] bg-[#fbfaf7] p-10 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e8f0e8] text-[#214e3b]"><LineChartIcon className="h-6 w-6" /></span><p className="mt-4 font-bold text-stone-700">아직 분석할 출석 기록이 없습니다</p><p className="mt-1 text-sm text-stone-400">출석 체크 화면에서 한 주차를 저장하면 추이와 기수별 비교가 표시됩니다.</p></section>; }
