import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ChevronDown, FolderPlus, Plus, Search, UserRoundPlus, UsersRound } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const statusLabels = { active: "재적", new: "새가족", dormant: "휴면", transferred: "전출" } as const;
type Status = keyof typeof statusLabels;

export default function Members() {
  const utils = trpc.useUtils();
  const { data: groups = [] } = trpc.groups.list.useQuery();
  const { data: members = [], isLoading } = trpc.members.list.useQuery();
  const [search, setSearch] = useState("");
  const [showMemberForm, setShowMemberForm] = useState(false);
  const [showGroupForm, setShowGroupForm] = useState(false);
  const [selectedGroupId, setSelectedGroupId] = useState<number | null>(null);
  const [memberName, setMemberName] = useState("");
  const [phone, setPhone] = useState("");
  const [status, setStatus] = useState<Status>("active");
  const [groupCode, setGroupCode] = useState("");
  const [groupName, setGroupName] = useState("");

  useEffect(() => { if (!selectedGroupId && groups[0]) setSelectedGroupId(groups[0].id); }, [groups, selectedGroupId]);
  const refresh = async () => { await Promise.all([utils.groups.list.invalidate(), utils.members.list.invalidate(), utils.dashboard.summary.invalidate(), utils.analytics.overview.invalidate()]); };
  const createGroup = trpc.groups.create.useMutation({ onSuccess: async group => { setSelectedGroupId(group.id); setGroupCode(""); setGroupName(""); setShowGroupForm(false); await refresh(); toast.success(`${group.name} 기수를 만들었습니다.`); }, onError: error => toast.error(error.message) });
  const createMember = trpc.members.create.useMutation({ onSuccess: async () => { setMemberName(""); setPhone(""); setStatus("active"); setShowMemberForm(false); await refresh(); toast.success("회원이 등록되었습니다."); }, onError: error => toast.error(error.message) });
  const filtered = useMemo(() => members.filter(member => `${member.name} ${member.groupName ?? ""} ${member.groupCode ?? ""}`.toLowerCase().includes(search.toLowerCase())), [members, search]);
  const grouped = useMemo(() => { const map = new Map<string, typeof filtered>(); for (const member of filtered) { const key = member.groupName || "미분류"; map.set(key, [...(map.get(key) ?? []), member]); } return Array.from(map.entries()); }, [filtered]);

  const submitMember = (event: FormEvent) => { event.preventDefault(); if (!selectedGroupId) return toast.error("먼저 기수/부서를 등록해 주세요."); createMember.mutate({ name: memberName.trim(), phone: phone.trim() || null, status, groupId: selectedGroupId }); };
  const submitGroup = (event: FormEvent) => { event.preventDefault(); if (!groupCode.trim() || !groupName.trim()) return toast.error("기수 코드와 이름을 입력해 주세요."); createGroup.mutate({ code: groupCode.trim(), name: groupName.trim() }); };

  return <div className="space-y-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold tracking-[0.14em] text-[#b66b3d]">MEMBER DIRECTORY</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight text-stone-800 sm:text-3xl">회원 명단</h1><p className="mt-2 text-sm text-stone-500">기수와 부서별로 회원을 관리합니다. 출석 대상은 재적·새가족 상태만 포함됩니다.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setShowGroupForm(value => !value)} className="h-11 rounded-xl border-[#d9d5cb] bg-white"><FolderPlus className="mr-2 h-4 w-4" />기수 추가</Button><Button onClick={() => { if (!groups.length) return toast.info("기수/부서를 먼저 추가해 주세요."); setShowMemberForm(value => !value); }} className="h-11 rounded-xl bg-[#214e3b] hover:bg-[#173a2b]"><UserRoundPlus className="mr-2 h-4 w-4" />회원 등록</Button></div></header>

    {showGroupForm && <form onSubmit={submitGroup} className="rounded-[1.5rem] border border-[#d4e2d1] bg-[#f5faf3] p-5"><div className="flex items-center justify-between"><div><p className="font-bold text-stone-800">기수 / 부서 추가</p><p className="mt-1 text-xs text-stone-500">예: 코드 07, 이름 07기 청년부</p></div><button type="button" onClick={() => setShowGroupForm(false)} className="text-xs font-semibold text-stone-400">닫기</button></div><div className="mt-4 grid gap-3 sm:grid-cols-[0.45fr_1fr_auto]"><input value={groupCode} onChange={event => setGroupCode(event.target.value)} placeholder="코드 (예: 07)" className="h-11 rounded-xl border border-[#d9d5cb] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#214e3b]" /><input value={groupName} onChange={event => setGroupName(event.target.value)} placeholder="기수/부서 이름 (예: 07기)" className="h-11 rounded-xl border border-[#d9d5cb] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#214e3b]" /><Button disabled={createGroup.isPending} className="h-11 rounded-xl bg-[#214e3b] hover:bg-[#173a2b]">{createGroup.isPending ? "추가 중" : "추가"}</Button></div></form>}

    {showMemberForm && <form onSubmit={submitMember} className="rounded-[1.5rem] border border-[#e9dacb] bg-[#fffaf3] p-5"><div className="flex items-center justify-between"><div><p className="font-bold text-stone-800">새 회원 등록</p><p className="mt-1 text-xs text-stone-500">필수 항목만 입력해도 출석부에 바로 추가됩니다.</p></div><button type="button" onClick={() => setShowMemberForm(false)} className="text-xs font-semibold text-stone-400">닫기</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input required value={memberName} onChange={event => setMemberName(event.target.value)} placeholder="이름 *" className="h-11 rounded-xl border border-[#d9d5cb] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#214e3b]" /><input value={phone} onChange={event => setPhone(event.target.value)} placeholder="연락처 (선택)" className="h-11 rounded-xl border border-[#d9d5cb] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#214e3b]" /><select aria-label="기수 선택" value={selectedGroupId ?? ""} onChange={event => setSelectedGroupId(Number(event.target.value))} className="h-11 rounded-xl border border-[#d9d5cb] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#214e3b]">{groups.map(group => <option key={group.id} value={group.id}>{group.name}</option>)}</select><select aria-label="상태 선택" value={status} onChange={event => setStatus(event.target.value as Status)} className="h-11 rounded-xl border border-[#d9d5cb] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#214e3b]"><option value="active">재적</option><option value="new">새가족</option><option value="dormant">휴면</option><option value="transferred">전출</option></select><Button disabled={createMember.isPending} className="h-11 rounded-xl bg-[#214e3b] hover:bg-[#173a2b]"><Plus className="mr-1 h-4 w-4" />{createMember.isPending ? "등록 중" : "등록"}</Button></div></form>}

    <section className="overflow-hidden rounded-[1.6rem] border border-[#e7e4dc] bg-white shadow-[0_8px_25px_rgba(68,62,48,0.04)]"><div className="flex flex-col gap-3 border-b border-[#efede7] p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="relative max-w-md flex-1"><Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-stone-400" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="이름 또는 기수/부서 검색" className="h-11 w-full rounded-xl bg-[#f7f6f1] pl-11 pr-4 text-sm outline-none focus:ring-2 focus:ring-[#214e3b]" /></div><p className="text-sm font-semibold text-stone-500">총 <span className="text-[#214e3b]">{members.length}</span>명</p></div>
      {isLoading ? <div className="p-10 text-center text-sm text-stone-400">회원 명단을 불러오는 중입니다.</div> : !members.length ? <EmptyMembers onAddGroup={() => setShowGroupForm(true)} /> : <div className="divide-y divide-[#efede7]">{grouped.map(([groupName, list]) => <MemberGroup key={groupName} groupName={groupName} members={list} />)}{!grouped.length && <div className="p-10 text-center text-sm text-stone-400">검색 결과가 없습니다.</div>}</div>}
    </section>
  </div>;
}

function MemberGroup({ groupName, members }: { groupName: string; members: { id: number; name: string; phone: string | null; status: Status; groupCode: string | null }[] }) { const [open, setOpen] = useState(true); return <section><button onClick={() => setOpen(value => !value)} className="flex w-full items-center justify-between bg-[#fcfbf8] px-5 py-3.5 text-left"><span className="font-bold text-stone-700">{groupName} <span className="ml-1 text-xs font-medium text-stone-400">{members.length}명</span></span><ChevronDown className={`h-4 w-4 text-stone-400 transition ${open ? "rotate-180" : ""}`} /></button>{open && <div className="divide-y divide-[#f0eee9] px-5">{members.map(member => <div key={member.id} className="flex min-h-16 items-center gap-3 py-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f1efe8] text-xs font-bold text-[#214e3b]">{member.name.slice(0, 1)}</span><div className="min-w-0"><p className="font-bold text-stone-800">{member.name}</p>{member.phone && <p className="mt-0.5 text-xs text-stone-400">{member.phone}</p>}</div><span className={`ml-auto rounded-full px-2.5 py-1 text-[11px] font-bold ${member.status === "new" ? "bg-[#fff0df] text-[#b66b3d]" : member.status === "active" ? "bg-[#e8f0e8] text-[#2d6a4f]" : "bg-stone-100 text-stone-500"}`}>{statusLabels[member.status]}</span></div>)}</div>}</section>; }
function EmptyMembers({ onAddGroup }: { onAddGroup: () => void }) { return <div className="p-10 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e8f0e8] text-[#214e3b]"><UsersRound className="h-6 w-6" /></span><p className="mt-4 font-bold text-stone-700">회원 명단이 비어 있습니다</p><p className="mt-1 text-sm text-stone-400">기수/부서를 먼저 추가한 뒤 회원을 등록해 주세요.</p><Button onClick={onAddGroup} className="mt-5 h-10 rounded-xl bg-[#214e3b] hover:bg-[#173a2b]"><FolderPlus className="mr-2 h-4 w-4" />첫 기수 추가</Button></div>; }
